### PR TITLE
test merge request

### PR DESCRIPTION
**Pull request by karanssj4**
Signed-off-by: Karan Raina <karan95raina@gmail.com>

### CODE REVIEW

**Comment by jeyserHiro** [comment]
> Signed-off-by: Karan Raina [karan95raina@gmail.com](mailto:karan95raina@gmail.com)

Hi

**Comment by anurag-k01** [comment]
# Commit #123 - Test Report

Execution Time: 67s

Test Run Between :

**Primary** : 172.0.2.21:3013

**Candidate** : 172.0.2.21:3013

| Regressions | Affected Flows | Covered Flows      | Affected APIs | Covered APIs       |
| ----------- | -------------- | ------------------ | ------------- | ------------------ |
| 8 Total     | 7 Affected     | 13 out of 20 total | 9 Affected    | 21 out of 30 total |

## Summary

#### Not Satisfied with the report ? [Change Settings](https://link-url-here.org)

| Incident                                                             | API                                                                                                                                                                                      |
|----------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| STATUS_CODE_CHANGED to 500                                           | POST /api/v0/Users/{id}/addNewMerchant<br><br>POST /api/v0/Users/{id}/addNewMerchant<br><br>POST /api/v0/Users/{id}/addNewMerchant<br><br>POST /api/v0/Transactions/recordNewTransaction |
| KEY_REMOVED at path : /ts4_primary<br>VALUE_MODIFIED at path : /type | GET /api/0/merchants/{id}                                                                                                                                                                |
| DATA_TYPE_CHANGED at path : /credit<br>VALUE_MODIFIED at path: /type | POST /api/v0/Users/{id}/addNewMerchant                                                                                                                                                   |
| VALUE_MODIFIED at path : /type                                       | GET /api/v0/Users/{id}/addNewMerchant<br><br>POST /api/v0/Users/{id}/addNewMerchant                                                                                                      |                                                                                                                                        |

### Top 10 Slowest APIs

| API                                            | Response Time     |
| ---------------------------------------------- | ----------------- |
| POST /api/v0/Users/registerUserViaOtp          | 0.06s (candidate) |
| POST /api/v0/Transactions/recordNewTransaction | 0.02s (candidate) |
| POST /api/v0/Users/{id}/addNewMerchant         | 0.02s (candidate) |
| GET /getUser/{id}/key_removed_example          | 0.02s (candidate) |
| POST /api/v0/Otps                              | 0.01s (candidate) |
| GET /api/v0/Merchants/{id}/transactions        | 0.01s (candidate) |
| POST /debug.cgi                                | 0.01s (candidate) |
| GET /api/v0/Merchants/{id}/settlements         | 0.01s (candidate) |
| GET /Top5RatedUsers/array_order_example        | 0.01s (candidate) |
| POST /api/v0/Merchants/{id}/getDailyCollection | 0.01s (candidate) |

<details>
<summary><strong>Test Instance Details</strong></summary>
<pre>
{
  "primaryHash": "http://172.31.25.31:3011",
  "candidateHash": "http://172.31.25.31:3013",
  "candidateBranchId": "main",
  "initialTimestamp": "2022-09-04T11:33:03.693Z",
  "finalTimestamp": "2022-09-07T11:33:01.746Z",
  "shouldStopOnFail": false,
  "isSmokeTest": false,
  "isSavedSessionOnlyTest": false,
  "sessionIds": null,
  "totalSessionCount": 5,
  "totalRequestCount": 33,
  "uniqueRequestCount": 33,
  "allDocumentedApiCount": 8,
  "allUndocumentedApiCount": 26,
  "testApiCount": 22,
  "totalSwaggerDocApiCount": 589,
  "coveredSwaggerDocApiCount": 8,
  "undocumentedApiCount": 14,
  "totalIssuesCount": 0,
  "openIssuesCount": 0,
  "shouldPlayDuplicateRequests": false,
  "shouldPlayDuplicateSessions": false,
  "description": "",
  "meta": {
    "ciEnvVars": {
      "isCi": true,
      "name": "GitHub Actions",
      "service": "github",
      "commit": "385e24317e26a42829ed3dad5c42e1354760835a",
      "build": "2954077561",
      "isPr": true,
      "branch": "main",
      "prBranch": "refs/pull/2/merge",
      "slug": "hypertestco/sample-ci-checks",
      "root": "/home/runner/work/sample-ci-checks/sample-ci-checks",
      "pr": 2
    }
  },
  "htEnvs": [],
  "minimumSeverity": "HIGH",
  "isSignoffRequired": true,
  "testExecutionOverheadTime": 16.61886,
  "reportGenerationOverheadTime": 11.805,
  "testRunVariables": {},
  "status": "FINISHED",
  "errorObj": null,
  "scheduledAt": "2022-09-07T11:33:05.370Z",
  "externalCheckRunId": "8227036119",
  "id": 29,
  "createdAt": "2022-09-07T11:33:05.383Z",
  "modifiedAt": "2022-09-07T11:33:23.441Z",
  "signoffs": {
    "signoffState": "PENDING",
    "type": "MANUAL",
    "signoffEmail": null,
    "signoffDate": null,
    "comments": "",
    "sendNotificationAt": "2022-09-07T11:43:23.465Z",
    "id": 24,
    "testId": 29
  }
}
</pre>

</details>

#### Manual Interventions:

[Force Skip this check](https://link-url-here.org)
[Force Fail this check](https://link-url-here.org)

**Comment by jeyserHiro** [comment]
<h1 dir="auto" style="box-sizing: border-box; font-size: 2em; margin-top: 0px !important; margin-right: 0px; margin-bottom: 16px; margin-left: 0px; font-weight: 600; line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-muted); color: rgb(201, 209, 217); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Commit #123 - Test Report</h1><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Execution Time: 67s</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Test Run Between :</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 600;">Primary</strong><span> </span>: 172.0.2.21:3013</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 600;">Candidate</strong><span> </span>: 172.0.2.21:3013</p>

Regressions | Affected Flows | Covered Flows | Affected APIs | Covered APIs
-- | -- | -- | -- | --
8 Total | 7 Affected | 13 out of 20 total | 9 Affected | 21 out of 30 total
[Force Fail this check](https://link-url-here.org/)
<details style="box-sizing: border-box; display: block; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><summary style="box-sizing: border-box; display: list-item; cursor: pointer;"><strong style="box-sizing: border-box; font-weight: 600;">Test Instance Details</strong></summary></details><h4 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 14px; font-weight: 600; line-height: 1.25; color: rgb(201, 209, 217); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Manual Interventions:</h4><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px !important; color: rgb(201, 209, 217); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://link-url-here.org/" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">Force Skip this check</a><br style="box-sizing: border-box;"><a href="https://link-url-here.org/" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">Force Fail this check</a></p>Commit #123 - Test Report
Execution Time: 67s

Test Run Between :

Primary : 172.0.2.21:3013

Candidate : 172.0.2.21:3013

Regressions	Affected Flows	Covered Flows	Affected APIs	Covered APIs
8 Total	7 Affected	13 out of 20 total	9 Affected	21 out of 30 total
Summary
Not Satisfied with the report ? [Change Settings](https://link-url-here.org/)
Incident	API
STATUS_CODE_CHANGED to 500	POST /api/v0/Users/{id}/addNewMerchant

POST /api/v0/Users/{id}/addNewMerchant

POST /api/v0/Users/{id}/addNewMerchant

POST /api/v0/Transactions/recordNewTransaction
KEY_REMOVED at path : /ts4_primary
VALUE_MODIFIED at path : /type	GET /api/0/merchants/{id}
DATA_TYPE_CHANGED at path : /credit
VALUE_MODIFIED at path: /type	POST /api/v0/Users/{id}/addNewMerchant
VALUE_MODIFIED at path : /type	GET /api/v0/Users/{id}/addNewMerchant

POST /api/v0/Users/{id}/addNewMerchant
Top 10 Slowest APIs
API	Response Time
POST /api/v0/Users/registerUserViaOtp	0.06s (candidate)
POST /api/v0/Transactions/recordNewTransaction	0.02s (candidate)
POST /api/v0/Users/{id}/addNewMerchant	0.02s (candidate)
GET /getUser/{id}/key_removed_example	0.02s (candidate)
POST /api/v0/Otps	0.01s (candidate)
GET /api/v0/Merchants/{id}/transactions	0.01s (candidate)
POST /debug.cgi	0.01s (candidate)
GET /api/v0/Merchants/{id}/settlements	0.01s (candidate)
GET /Top5RatedUsers/array_order_example	0.01s (candidate)
POST /api/v0/Merchants/{id}/getDailyCollection	0.01s (candidate)
Test Instance Details
Manual Interventions:
[Force Skip this check](https://link-url-here.org/)
[Force Fail this check](https://link-url-here.org/)

**Comment by anurag-k01** [comment]
<html>
  <head>
  
  </head>
<body>
  <div>
    <h1>Commit #123 - Test Report</h1>
  </div>
  <div>
    <p><strong>Manual Interventions:</strong></p>
    <div>
    <a href="/">Force Skip this check</a> &nbsp;
    <a href="/">Force Fail this check</a>
    </div>
    </div>
</br>
  <div >
    <h2>
      Summary 
    </h2>
    <table class="rwd-table">
      <tbody>
        <tr>
          <th>Regressions</th>
          <th>Covered Flows</th>
          <th>Affected APIs </th>
          <th>Covered APIs </th>
        </tr>
        <tr>
          <td data-th="incompatibleChange">8 Total</td>
        <td data-th="endpoint">13 out of 20 total</td>
          <td data-th="endpoint">9 Affected</td>
          <td data-th="endpoint">21 out of 30 total</td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="container" >
    <div >
      <h2>
        Details 
      </h2>
<div><strong>  Not Satisfied with the report ?
&nbsp;
   <a href="/">Change Settings</a></strong>
<div>
    </div>
    <br />
    <table class="rwd-table" >
      <tbody>
        <tr>
          <th>Incident</th>
          <th>API</th>
        </tr>
        <tr>
          <td data-th="incident">
            STATUS_CODE_CHANGED to 500
          </td>
          <td data-th="api">
                 POST  /api/v0/Users/{id}/addNewMerchant
</br>
            POST   /api/v0/Users/{id}/addNewMerchant
</br>
        POST  /api/v0/Users/{id}/addNewMerchant
</br>
             POST  /api/v0/Transactions/recordNewTransaction
          </td>
        </tr>
        <tr>
          <td data-th="incident">
            KEY_REMOVED at path : /ts4_primary
            <p>VALUE_MODIFIED at path :  /type</p>
          </td>
          <td data-th="endpoint">GET /api/0/merchants/{id}</td>
        </tr>
        <tr>
          <td data-th="incident">
            DATA_TYPE_CHANGED at path :  /credit
            <p>VALUE_MODIFIED at path: /type</p>
          </td>
          <td data-th="api">POST  /api/v0/Users/{id}/addNewMerchant</td>
        </tr>
        <tr>
          <td data-th="incident">VALUE_MODIFIED at path : /type</td>
          <td data-th="api">
            GET  /api/v0/Users/{id}/addNewMerchant
</br> 
           POST  /api/v0/Users/{id}/addNewMerchant
          </td>
        </tr>
      </tbody>
    </table>
  </div>
<h3>Top 10 Slowest APIs : </h3>
<table class="rwd-table">
          <tbody>
            <tr>
              <th>API</th>
              <th>Response Time</th>
            </tr>
            <tr>
              <td data-th="api">POST /api/v0/Users/registerUserViaOtp</td>
              <td data-th="responseTime">0.06s (candidate)</td>
            </tr>
        <tr>
              <td data-th="api">
  POST /api/v0/Transactions/recordNewTransaction</td>
              <td data-th="responseTime">0.02s (candidate)</td>
            </tr>
        <tr>
              <td data-th="api">POST /api/v0/Users/{id}/addNewMerchant</td>
              <td data-th="responseTime">0.02s (candidate)</td>
            </tr>
        <tr>
              <td data-th="api">GET /getUser/{id}/key_removed_example</td>
              <td data-th="responseTime">0.02s (candidate)</td>
            </tr>
        <tr>
              <td data-th="api">POST /api/v0/Otps</td>
              <td data-th="responseTime">0.01s (candidate)</td>
            </tr>
        <tr>
              <td data-th="api">GET /api/v0/Merchants/{id}/transactions</td>
              <td data-th="responseTime">0.01s (candidate)</td>
            </tr>
      <tr>
              <td data-th="api">POST /debug.cgi</td>
              <td data-th="responseTime">0.01s (candidate)</td>
            </tr>
      <tr>
              <td data-th="api">GET /api/v0/Merchants/{id}/settlements</td>
              <td data-th="responseTime">0.01s (candidate)</td>
            </tr>
      <tr>
              <td data-th="api">GET /Top5RatedUsers/array_order_example</td>
              <td data-th="responseTime">0.01s (candidate)</td>
            </tr>
      <tr>
              <td data-th="api">POST /api/v0/Merchants/{id}/getDailyCollection</td>
              <td data-th="responseTime">0.01s (candidate)</td>
            </tr>
          </tbody>
        </table>
</div>
<div>
<details>
<summary><strong>Test Instance Details</strong></summary>
<pre>
{
"primaryHash": "http://172.31.25.31:3011",
"candidateHash": "http://172.31.25.31:3013",
"candidateBranchId": "main",
"initialTimestamp": "2022-09-04T11:33:03.693Z",
"finalTimestamp": "2022-09-07T11:33:01.746Z",
"shouldStopOnFail": false,
"isSmokeTest": false,
"isSavedSessionOnlyTest": false,
"sessionIds": null,
"totalSessionCount": 5,
"totalRequestCount": 33,
"uniqueRequestCount": 33,
"allDocumentedApiCount": 8,
"allUndocumentedApiCount": 26,
"testApiCount": 22,
"totalSwaggerDocApiCount": 589,
"coveredSwaggerDocApiCount": 8,
"undocumentedApiCount": 14,
"totalIssuesCount": 0,
"openIssuesCount": 0,
"shouldPlayDuplicateRequests": false,
"shouldPlayDuplicateSessions": false,
"description": "",
"meta": {
  "ciEnvVars": {
    "isCi": true,
    "name": "GitHub Actions",
    "service": "github",
    "commit": "385e24317e26a42829ed3dad5c42e1354760835a",
    "build": "2954077561",
    "isPr": true,
    "branch": "main",
    "prBranch": "refs/pull/2/merge",
    "slug": "hypertestco/sample-ci-checks",
    "root": "/home/runner/work/sample-ci-checks/sample-ci-checks",
    "pr": 2
  }
},
"htEnvs": [],
"minimumSeverity": "HIGH",
"isSignoffRequired": true,
"testExecutionOverheadTime": 16.61886,
"reportGenerationOverheadTime": 11.805,
"testRunVariables": {},
"status": "FINISHED",
"errorObj": null,
"scheduledAt": "2022-09-07T11:33:05.370Z",
"externalCheckRunId": "8227036119",
"id": 29,
"createdAt": "2022-09-07T11:33:05.383Z",
"modifiedAt": "2022-09-07T11:33:23.441Z",
"signoffs": {
  "signoffState": "PENDING",
  "type": "MANUAL",
  "signoffEmail": null,
  "signoffDate": null,
  "comments": "",
  "sendNotificationAt": "2022-09-07T11:43:23.465Z",
  "id": 24,
  "testId": 29
}
}
</pre>

</details>
</div>

</body>
</html>

**Pull request closed without merging**
